CREATE TYPE data_kubun AS ENUM ('1', '2', '3', '4', '5', '6', '7', 'A', 'B', '0');
CREATE TABLE jv_ra_race (
    race_id char(14) PRIMARY KEY,
    data_kubun data_kubun not null,
    record_created_at date not null,
    race_date date not null,
    jyo_code jyo_code not null,
    kaiji char(2) not null,
    nichiji char(2) not null,
    race_num char(2) not null,
    youbi_code youbi_code not null,
    toku_num char(4) not null,
    hondai char(60) not null,
    fukudai char(60) not null,
    kakko char(60) not null,
    hondai_eng char(120) not null,
    fukudai_eng char(120) not null,
    kakko_eng char(120) not null,
    ryakusyo_10 char(20) not null,
    ryakusyo_6 char(12) not null,
    ryakusyo_3 char(6) not null,
    kubun char(1) not null,
    nkai char(3) not null,
    grade_code grade_code not null,
    grade_code_before grade_code not null,
    syubetu_code syubetu_code not null,
    kigo_code char(3) not null,
    jyuryo_code char(1) not null,
    jyoken_code_2 char(3) not null,
    jyoken_code_3 char(3) not null,
    jyoken_code_4 char(3) not null,
    jyoken_code_5_years_old_and_over char(3) not null,
    jyoken_code_youngest char(3) not null,
    jyoken_name char(60) not null,
    kyori integer not null,
    kyori_before integer not null,
    track_code char(2) not null,
    track_code_before char(2) not null,
    course_kubun_code char(2) not null,
    course_kubun_code_before char(2) not null,
    honsyokin integer [7] not null,
    honsyokin_before integer [5] not null,
    fukasyokin integer [5] not null,
    fukasyokin_before integer [3] not null,
    hasso_time time not null,
    hasso_time_before time not null,
    toroku_tosu integer not null,
    syusso_tosu integer not null,
    nyusen_tosu integer not null,
    tenko_code char(1) not null,
    siba_baba_code char(1) not null,
    dirt_baba_code char(1) not null,
    lap_time real [25] null,
    syogai_mile_time real null,
    haron_time_s3 real null,
    haron_time_s4 real null,
    haron_time_l3 real null,
    haron_time_l4 real null,
    corner char(1) [4] null,
    syukaisu char(1) [4] null,
    jyuni char(70) [4] null
)